# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI (Gradle, Temurin, JDK 11)

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: 'x64'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Run unit tests
        run: ./gradlew :tests:test --tests "com.team3gdx.tests.*"
  discord-notification:
    runs-on: ubuntu-latest
    needs: [windows-tests,ubuntu-tests,macos-tests]
    steps:
      - name: This, I like!
        if: ${{ github.event_name == 'push' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: "Ilshidur/action-discord@0.3.2"
        with:
          args: 'Jackpot! All unit tests across all platforms are passing - this, I like!'